import { ArrowRight, MapPin } from "lucide-react";
import { Link } from "react-router-dom";
import SEO from "../components/SEO";
import { tours } from "../data/tours";
import VehicleFleetSection from "../components/VehicleFleetSection";
import { vehicles } from "../data/vehicles";
import { useLanguage } from "../context/LanguageContext";
import { PageIntro } from "./Services";
export default function Tours() { const { lang, t } = useLanguage(); const travelVehicles = vehicles.filter(vehicle => ["etios", "innova", "innova-crysta", "cruiser", "tempo-traveller", "bus"].includes(vehicle.id)); return <><SEO title="Rajasthan Tour Packages from Bikaner" description="बीकानेर से राजस्थान टूर और यात्रा कार्यक्रम के लिए श्री गुसांई जी टूर & ट्रैवल्स से संपर्क करें।" path="/tours" /><PageIntro eyebrow={t.tours.eyebrow} title={t.tours.title} accent={t.tours.accent} description={t.tours.description} /><section className="section"><div className="container"><div className="tour-page-grid">{tours.map((tour, index) => <article className="tour-card" key={tour.id}><div className="tour-number">{String(index + 1).padStart(2, "0")}</div><MapPin size={27} /><h2>{lang === "hi" ? tour.titleHi : tour.titleEn}</h2><ul>{(lang === "hi" ? tour.highlightsHi : tour.highlightsEn).map(item => <li key={item}>{item}</li>)}</ul><p className="tour-note">{t.common.customisable}</p><Link to="/booking" className="text-link">{t.common.enquire}<ArrowRight size={17} /></Link></article>)}</div></div></section><section className="section tour-vehicles-section"><div className="container"><div className="section-heading"><div><div className="eyebrow">{lang === "hi" ? "यात्रा के वाहन" : "Travel vehicles"}</div><h2>{lang === "hi" ? "टूर और यात्रा के लिए वाहन" : "Vehicles for tours and travel"}</h2></div><p>{lang === "hi" ? "फैमिली ट्रिप, राजस्थान टूर, बीकानेर लोकल, आउटस्टेशन, ग्रुप टूर, धार्मिक यात्रा और एयरपोर्ट या रेलवे ट्रांसफर के लिए उपलब्धता पूछें।" : "Ask about availability for family trips, Rajasthan tours, Bikaner local travel, outstation, group and religious trips, and airport or railway transfers."}</p></div><VehicleFleetSection vehicles={travelVehicles} className="tour-fleet" /></div></section></>; }
