import { Car, Users, Sparkles, CalendarDays } from "lucide-react";
import SEO from "../components/SEO";
import VehicleFleetSection from "../components/VehicleFleetSection";
import { vehicles } from "../data/vehicles";
import { useLanguage } from "../context/LanguageContext";
import { useWhatsApp } from "../hooks/useWhatsApp";

export default function Wedding() {
  const { lang, t } = useLanguage();
  const { quickEnquiry } = useWhatsApp();
  const cards = [[<Sparkles />, lang === "hi" ? "बारात" : "Baraat Transportation", lang === "hi" ? "शादी समारोह के लिए वाहन आवश्यकता साझा करें।" : "Share your vehicle requirements for the wedding event."], [<Users />, lang === "hi" ? "परिवार एवं मेहमान" : "Family & Guests", lang === "hi" ? "परिवार और मेहमानों की यात्रा के लिए संपर्क करें।" : "Contact us for family and guest transportation."], [<Car />, lang === "hi" ? "वाहन व्यवस्था" : "Vehicle Arrangement", lang === "hi" ? "उपलब्धता के लिए संपर्क करें।" : "Contact us for availability."], [<CalendarDays />, lang === "hi" ? "तारीख साझा करें" : "Share Your Date", lang === "hi" ? "शादी की तारीख और यात्रा विवरण साझा करें।" : "Share your wedding date and travel details."]];
  return <><SEO title="Wedding Transportation in Bikaner | Shri Gursai Ji" description="शादी-विवाह, बारात, परिवार और मेहमानों के लिए वाहन व्यवस्था हेतु संपर्क करें।" path="/wedding" /><main><section className="wedding-hero"><div className="container"><div className="eyebrow"><Sparkles size={16} />{t.wedding.eyebrow}</div><h1>{t.wedding.title}<span>{t.wedding.accent}</span></h1><p>{t.wedding.description}</p><button type="button" className="btn btn-light btn-large" onClick={() => quickEnquiry("शादी के लिए वाहन")}>{lang === "hi" ? "शादी के लिए वाहन पूछें" : "Enquire about wedding vehicles"}</button></div></section><section className="section"><div className="container"><div className="wedding-service-grid">{cards.map(([icon, title, text]) => <div key={title}>{icon}<h3>{title}</h3><p>{text}</p></div>)}</div></div></section><section className="section wedding-vehicles-section"><div className="container"><div className="section-heading"><div><div className="eyebrow">{lang === "hi" ? "शादी-विवाह के लिए" : "For weddings"}</div><h2>{lang === "hi" ? "वाहन व्यवस्था" : "Wedding vehicle arrangements"}</h2></div><p>{lang === "hi" ? "बारात, परिवार एवं मेहमानों के लिए आवश्यकता अनुसार वाहनों की व्यवस्था की जा सकती है।" : "Vehicles can be arranged as needed for the baraat, family and guests."}</p></div><VehicleFleetSection vehicles={vehicles} className="wedding-fleet" /><button type="button" className="btn btn-primary wedding-vehicle-cta" onClick={() => quickEnquiry("शादी-विवाह के लिए वाहन व्यवस्था")}>{lang === "hi" ? "शादी के लिए वाहन पूछें" : "Enquire about wedding vehicles"}</button></div></section></main></>;
}
