import { useState } from "react";
import { CheckCircle2, Send } from "lucide-react";
import { buildWhatsAppLink } from "../data/business";
import { services } from "../data/services";
import { vehicles } from "../data/vehicles";
import { useLanguage } from "../context/LanguageContext";
const initial = { name: "", mobile: "", service: "", date: "", pickup: "", destination: "", passengers: "", vehicle: "", tripType: "", details: "" };
export default function BookingForm() {
  const { lang } = useLanguage(); const [form, setForm] = useState(initial); const [errors, setErrors] = useState({}); const [success, setSuccess] = useState(false); const label = (hi, en) => lang === "hi" ? hi : en;
  const change = event => { const { name, value } = event.target; setForm(current => ({ ...current, [name]: value })); setErrors(current => ({ ...current, [name]: "" })); };
  const submit = event => { event.preventDefault(); const next = {}; if (!form.name.trim()) next.name = label("नाम आवश्यक है", "Name is required"); if (!/^[6-9]\d{9}$/.test(form.mobile.trim())) next.mobile = label("मान्य 10 अंकों का मोबाइल नंबर दर्ज करें", "Enter a valid 10-digit mobile number"); if (!form.service) next.service = label("सेवा चुनें", "Select a service"); if (!form.pickup.trim()) next.pickup = label("पिकअप स्थान आवश्यक है", "Pickup location is required"); if (!form.tripType) next.tripType = label("ट्रिप प्रकार चुनें", "Select trip type"); setErrors(next); if (Object.keys(next).length) return; const service = services.find(item => item.id === form.service); const vehicle = vehicles.find(item => item.id === form.vehicle); const message = `नमस्ते,\n\nमुझे श्री गुसांई जी टूर & ट्रैवल्स से वाहन बुक करना है।\n\nनाम: ${form.name}\nमोबाइल: ${form.mobile}\nसेवा: ${service?.titleHi || "-"}\nयात्रा तारीख: ${form.date || "-"}\nपिकअप: ${form.pickup}\nगंतव्य: ${form.destination || "-"}\nयात्री: ${form.passengers || "-"}\nवाहन: ${vehicle?.nameHi || "-"}\nट्रिप प्रकार: ${form.tripType}\nअन्य जानकारी: ${form.details || "-"}`; setSuccess(true); window.open(buildWhatsAppLink(message), "_blank", "noopener,noreferrer"); };
  return <form className="booking-form" onSubmit={submit} noValidate>{success && <div className="success-message"><CheckCircle2 size={20} />{label("जानकारी WhatsApp पर भेजी जा रही है।", "Your enquiry is being sent via WhatsApp.")}</div>}<div className="form-grid"><Field label={label("नाम", "Name")} name="name" value={form.name} onChange={change} error={errors.name} /><Field label={label("मोबाइल नंबर", "Mobile Number")} name="mobile" value={form.mobile} onChange={change} error={errors.mobile} inputMode="numeric" placeholder="98XXXXXXXX" /><Select label={label("सेवा", "Service")} name="service" value={form.service} onChange={change} error={errors.service} options={services.map(item => [item.id, lang === "hi" ? item.titleHi : item.titleEn])} /><Field label={label("यात्रा तारीख", "Travel Date")} name="date" type="date" value={form.date} onChange={change} /><Field label={label("पिकअप स्थान", "Pickup Location")} name="pickup" value={form.pickup} onChange={change} error={errors.pickup} /><Field label={label("गंतव्य", "Destination")} name="destination" value={form.destination} onChange={change} /><Field label={label("यात्रियों की संख्या", "Passengers")} name="passengers" type="number" min="1" value={form.passengers} onChange={change} /><Select label={label("वाहन", "Vehicle")} name="vehicle" value={form.vehicle} onChange={change} options={vehicles.map(item => [item.id, lang === "hi" ? item.nameHi : item.nameEn])} /><Select label={label("ट्रिप प्रकार", "Trip Type")} name="tripType" value={form.tripType} onChange={change} error={errors.tripType} options={[["one-way", label("वन वे", "One Way")], ["round-trip", label("राउंड ट्रिप", "Round Trip")], ["local", label("लोकल", "Local")], ["outstation", label("आउटस्टेशन", "Outstation")], ["wedding", label("शादी-विवाह", "Wedding")], ["tour", label("टूर", "Tour")]]} /><div className="form-field full"><label>{label("अन्य जानकारी", "Additional Details")}</label><textarea name="details" rows="4" value={form.details} onChange={change} placeholder={label("अपनी यात्रा के बारे में जानकारी दें...", "Tell us about your journey...")} /></div></div><button type="submit" className="btn btn-whatsapp submit-button"><Send size={18} />{label("WhatsApp पर भेजें", "Send via WhatsApp")}</button></form>;
}
function Field({ label, name, type = "text", value, onChange, error, ...props }) { return <div className="form-field"><label>{label} *</label><input type={type} name={name} value={value} onChange={onChange} {...props} />{error && <small className="form-error">{error}</small>}</div>; }
function Select({ label, name, value, onChange, options, error }) { return <div className="form-field"><label>{label}{name !== "vehicle" && " *"}</label><select name={name} value={value} onChange={onChange}><option value="">चुनें / Select</option>{options.map(([id, text]) => <option value={id} key={id}>{text}</option>)}</select>{error && <small className="form-error">{error}</small>}</div>; }
