import { createContext, useContext, useEffect, useState } from "react";

const LanguageContext = createContext(null);
const copy = {
  hi: { nav: { home: "होम", services: "सेवाएं", fleet: "वाहन", tours: "टूर पैकेज", wedding: "शादी-विवाह", gallery: "गैलरी", about: "हमारे बारे में", contact: "संपर्क करें", booking: "बुकिंग", book: "अभी बुक करें" }, common: { call: "कॉल करें", whatsapp: "WhatsApp करें", enquire: "पूछताछ करें", learn: "और जानें", bikaner: "बीकानेर, राजस्थान", customisable: "यात्रा की तारीख और आवश्यकता के अनुसार पैकेज तैयार किया जा सकता है।" }, hero: { eyebrow: "बीकानेर की यात्रा सेवा", title1: "विवाह-शादी व टूर प्रोग्रामों में", title2: "इनोवा, इटियोस किराये पर", description: "हमारे यहां पर विवाह-शादी व टूर प्रोग्रामों में इनोवा, इटियोस आदि गाड़ियां किराये के लिए संपर्क करें।", primary: "99501-10771 अभी कॉल करें", secondary: "WhatsApp करें" }, services: { eyebrow: "हमारी सेवाएं", title: "आपकी यात्रा के लिए", accent: "सरल समाधान", description: "आपकी यात्रा की जरूरत के अनुसार वाहन और यात्रा व्यवस्था के लिए हमसे सीधे संपर्क करें।" }, fleet: { eyebrow: "हमारे वाहन", title: "आपके सफर के लिए", accent: "वाहन विकल्प", description: "उपलब्ध वाहन और आपकी यात्रा की आवश्यकता के बारे में जानकारी के लिए संपर्क करें।" }, tours: { eyebrow: "टूर प्रोग्राम", title: "राजस्थान घूमने की", accent: "यात्रा योजना", description: "आपकी तारीख और यात्रा की जरूरत के अनुसार टूर की योजना बनाई जा सकती है।" }, wedding: { eyebrow: "शादी-विवाह", title: "आपके खास दिन के लिए", accent: "वाहन व्यवस्था", description: "बारात, परिवार, मेहमानों और विवाह समारोह से जुड़ी यात्रा आवश्यकताओं के लिए संपर्क करें।", button: "शादी के लिए पूछताछ करें" }, about: { eyebrow: "हमारे बारे में", title: "स्थानीय सेवा,", accent: "सीधा संपर्क।", description: "श्री गुसांई जी टूर & ट्रैवल्स, बीकानेर में कार किराये, शादी-विवाह और टूर प्रोग्राम से जुड़ी यात्रा आवश्यकताओं के लिए संपर्क सेवा प्रदान करता है।" }, contact: { eyebrow: "संपर्क करें", title: "बुकिंग के लिए", accent: "सीधे बात करें" }, footer: { quick: "क्विक लिंक्स", services: "सेवाएं", contact: "संपर्क", rights: "सर्वाधिकार सुरक्षित।" } },
  en: { nav: { home: "Home", services: "Services", fleet: "Fleet", tours: "Tour Packages", wedding: "Wedding", gallery: "Gallery", about: "About", contact: "Contact", booking: "Booking", book: "Book Now" }, common: { call: "Call", whatsapp: "WhatsApp", enquire: "Enquire", learn: "Learn More", bikaner: "Bikaner, Rajasthan", customisable: "Packages are arranged around your travel dates and requirements." }, hero: { eyebrow: "Bikaner Travel Service", title1: "Innova, Etios and more", title2: "for weddings and tours", description: "Contact Shri Gursai Ji Tour & Travels in Bikaner to hire Innova, Etios and other vehicles for weddings and tour programs.", primary: "Call 99501-10771 now", secondary: "WhatsApp Us" }, services: { eyebrow: "Our Services", title: "Simple solutions for", accent: "your journey", description: "Contact us directly for vehicle and travel arrangements according to your requirements." }, fleet: { eyebrow: "Our Vehicles", title: "Vehicle options for", accent: "your journey", description: "Contact us for vehicle availability and travel requirements." }, tours: { eyebrow: "Tour Programs", title: "Plan your", accent: "Rajasthan journey", description: "Tour plans can be arranged according to your dates and requirements." }, wedding: { eyebrow: "Wedding Transportation", title: "Vehicle arrangements for", accent: "your special day", description: "Contact us for baraat, family, guest and wedding-event transportation requirements.", button: "Wedding Enquiry" }, about: { eyebrow: "About Us", title: "Local service,", accent: "direct contact.", description: "Shri Gursai Ji Tour & Travels provides a contact service in Bikaner for car rental, wedding transportation and tour program requirements." }, contact: { eyebrow: "Contact", title: "Talk to us", accent: "directly for booking" }, footer: { quick: "Quick Links", services: "Services", contact: "Contact", rights: "All rights reserved." } }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("gursai-lang") === "en" ? "en" : "hi");
  useEffect(() => { document.documentElement.lang = lang; localStorage.setItem("gursai-lang", lang); }, [lang]);
  return <LanguageContext.Provider value={{ lang, setLang, toggleLang: () => setLang(value => value === "hi" ? "en" : "hi"), t: copy[lang] }}>{children}</LanguageContext.Provider>;
}
export function useLanguage() { const context = useContext(LanguageContext); if (!context) throw new Error("useLanguage must be used inside LanguageProvider"); return context; }
